require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'FinanceApp' do
  # Pods for FinanceApp
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'FinanceAppTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'FinanceApp-tvOS' do
  # Pods for FinanceApp-tvOS

  target 'FinanceApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
